### ISSUE TITLE
Suggestion: Make private functions static and remove them from header

### ISSUE THREAD

**Issue by justinmeiners** [matteotiziano/nelder-mead#1]
Many of the internal functions such as `compare` probably don't need to be exposed. These can be left in the `.c` file with a `static` prefix.

Thanks!

**Comment by matteotiziano** [comment]
That is a good point. I did a refactoring to compartmentalize all different data types and functionalities. Might be overkill for such a small project, but I think it is easier to extend now.

**Comment by justinmeiners** [comment]
Great, just FYI, looking at your account, I thought this project might have been dead, so I did a lot of work in my own fork.  You may want to look at it.

A few other things included:
- allocating all the simplex points up front in one buffer. This ensures the number of mallocs is constant, instead of linear in the dimension. 
- in your swap function you don't need to copy the entire point buffer, just swap pointers.
- Comparison function doesn't need to branch.
- Preference: I changed the flat arrays of double's instead of point_t. This may be a style thing, but it does make the callback function more natural in that it just takes an array of doubles, and returns a double.

**Comment by matteotiziano** [comment]
Yeah, I am definitely not very active on GitHub. Anyway, this code was made for research purposes, so I really appreciate your feedback, I will check your fork!
