### ISSUE TITLE
Build fails, no referece to c math library

### ISSUE THREAD

**Issue by m4r35n357** [matteotiziano/nelder-mead#3]
Not sure if you are maintaining this, but here is my attempt at a fix:
```
$ git diff
diff --git a/Makefile b/Makefile
index 2309fe7..d0ae8a6 100644
--- a/Makefile
+++ b/Makefile
@@ -5,7 +5,7 @@ BIN = nm
 SRC = main.c nelder_mead.c point.c ackley.c
 
 compile:
-       gcc $(FLAGS) $(CC_OPT) -o $(BIN) $(SRC)
+       gcc $(FLAGS) $(CC_OPT) -o $(BIN) $(SRC) -lm
 
 test: compile
        time ./$(BIN) -2.10 -3.04 4.50 

```

**Comment by m4r35n357** [comment]
Incidentally, I have been working on the structure to make it easier to add models (without changing the algorithm!), if you are interested in what I have done, let me know.

**Comment by matteotiziano** [comment]
hello! yes, for sure, I'd be interested to see your improvements, thanks!

**Comment by m4r35n357** [comment]
[EDIT] email sent! - original message follows ;)
Probably easiest to send you a bare repo of my local work if you give me an email address, or if that is no good, I could either upload a new project, or try forking here and update it, do you have a preference?  Bear in mind that I am self-taught and non-pro, but I have added a couple of extra examples, beefed up the Makefile, and done a big (huge?) structural update (leaving the algorithm unchanged apart from minor renaming).
